version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  user-service:
    build: ./user-service
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: user_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: supersecretkey
      PORT: 8080
    ports:
    - "8081:8080"
    depends_on:
      - db
      - redis

  task-service:
    build: ./task-service
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: task_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: supersecretkey
      PORT: 8080
    ports:
    - "8082:8080" 
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5174:80"
    depends_on:
      - user-service
      - task-service

volumes:
  pgdata:

